# Generated by Django 4.0.3 on 2022-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='image',
            field=models.ImageField(upload_to='Core', verbose_name='Imagen de perfil'),
        ),
    ]
