# Generated by Django 4.0.3 on 2022-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Universidad')),
                ('degree', models.CharField(max_length=255, verbose_name='Título')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Fecha finalización')),
                ('status', models.CharField(blank=True, choices=[('C', 'Cursando'), ('G', 'Graduado')], max_length=1, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Educación',
                'ordering': ['-created'],
            },
        ),
    ]
