# Generated by Django 4.0.3 on 2022-04-29 00:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='Nota/Observación'),
        ),
    ]
