# Generated by Django 4.0.3 on 2022-04-25 21:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('degree', models.CharField(max_length=255, verbose_name='Título')),
                ('postgraduate', models.CharField(max_length=255, verbose_name='Posgrado')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('profile', ckeditor.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='Perfil')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
