# Generated by Django 4.0.3 on 2022-04-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Admin_about',
        ),
    ]
