# Generated by Django 4.0.3 on 2022-04-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_about_admin_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_about',
            new_name='AdminAbout',
        ),
    ]
