# Generated by Django 4.0.3 on 2022-04-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_admin_about_adminabout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAbout',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Acerca de'},
        ),
    ]
