# Generated by Django 4.0.3 on 2022-04-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_adminabout_about_alter_about_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='update',
            new_name='updated',
        ),
    ]
