# Generated by Django 4.0.3 on 2022-04-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created'], 'verbose_name': 'Experiencia'},
        ),
    ]
