# Generated by Django 4.0.3 on 2022-04-29 02:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='core_skills',
            field=ckeditor.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='Aptitudes principales'),
        ),
    ]
