# Generated by Django 4.0.3 on 2022-04-29 03:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('C', 'Certificado'), ('R', 'Reconocimiento')], max_length=1, null=True, verbose_name='Certificado/reconocimiento')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('institution', models.CharField(max_length=255, verbose_name='Institución')),
                ('observation', ckeditor.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='observación')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificado - reconocimiento',
            },
        ),
    ]
