# Generated by Django 4.0.3 on 2022-04-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='type',
            field=models.CharField(blank=True, choices=[('Certificado', 'Certificado'), ('Reconocimiento', 'Reconocimiento')], max_length=14, null=True, verbose_name='Certificado/reconocimiento'),
        ),
    ]
