# Generated by Django 4.0.3 on 2022-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_awards_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='observation',
            field=models.CharField(default=1, max_length=255, verbose_name='observación'),
            preserve_default=False,
        ),
    ]
