# Generated by Django 4.0.3 on 2022-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_awards_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='observación'),
        ),
    ]
